name: Deploy to github pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: React build
    runs-on: ubuntu-latest
    steps:
      # checkout files
      - uses: actions/checkout@v3

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./